var namespaceboost_1_1simd =
[
    [ "detail", null, [
      [ "simd_storage", "structboost_1_1simd_1_1detail_1_1simd__storage.html", null ],
      [ "storage_of", "structboost_1_1simd_1_1detail_1_1storage__of.html", null ],
      [ "storage_status", "structboost_1_1simd_1_1detail_1_1storage__status.html", null ]
    ] ],
    [ "ext", "namespaceboost_1_1simd_1_1ext.html", "namespaceboost_1_1simd_1_1ext" ],
    [ "aggregate_storage", "structboost_1_1simd_1_1aggregate__storage.html", null ],
    [ "as_logical", "structboost_1_1simd_1_1as__logical.html", null ],
    [ "assert_tag", "structboost_1_1simd_1_1assert__tag.html", null ],
    [ "avx2_", "structboost_1_1simd_1_1avx2__.html", null ],
    [ "avx_", "structboost_1_1simd_1_1avx__.html", null ],
    [ "cardinal_of", "structboost_1_1simd_1_1cardinal__of.html", null ],
    [ "emulation", "structboost_1_1simd_1_1emulation.html", null ],
    [ "expected_cardinal", "structboost_1_1simd_1_1expected__cardinal.html", null ],
    [ "extension_of", "structboost_1_1simd_1_1extension__of.html", null ],
    [ "fast_tag", "structboost_1_1simd_1_1fast__tag.html", null ],
    [ "fma3_", "structboost_1_1simd_1_1fma3__.html", null ],
    [ "fma4_", "structboost_1_1simd_1_1fma4__.html", null ],
    [ "is_not_scalar", "structboost_1_1simd_1_1is__not__scalar.html", null ],
    [ "is_scalar", "structboost_1_1simd_1_1is__scalar.html", null ],
    [ "limits", "structboost_1_1simd_1_1limits.html", "structboost_1_1simd_1_1limits" ],
    [ "logical", "structboost_1_1simd_1_1logical.html", "structboost_1_1simd_1_1logical" ],
    [ "logical_", "structboost_1_1simd_1_1logical__.html", null ],
    [ "mic_", "structboost_1_1simd_1_1mic__.html", null ],
    [ "native_storage", "structboost_1_1simd_1_1native__storage.html", null ],
    [ "neon64_", "structboost_1_1simd_1_1neon64__.html", null ],
    [ "neon_", "structboost_1_1simd_1_1neon__.html", null ],
    [ "pack", "classboost_1_1simd_1_1pack.html", "classboost_1_1simd_1_1pack" ],
    [ "pack_", "structboost_1_1simd_1_1pack__.html", null ],
    [ "qpx_", "structboost_1_1simd_1_1qpx__.html", null ],
    [ "real_of", "structboost_1_1simd_1_1real__of.html", null ],
    [ "scalar_storage", "structboost_1_1simd_1_1scalar__storage.html", null ],
    [ "simd_", "structboost_1_1simd_1_1simd__.html", null ],
    [ "simd_emulation_", "structboost_1_1simd_1_1simd__emulation__.html", null ],
    [ "sse2_", "structboost_1_1simd_1_1sse2__.html", null ],
    [ "sse3_", "structboost_1_1simd_1_1sse3__.html", null ],
    [ "sse4_1_", "structboost_1_1simd_1_1sse4__1__.html", null ],
    [ "sse4_2_", "structboost_1_1simd_1_1sse4__2__.html", null ],
    [ "sse4a_", "structboost_1_1simd_1_1sse4a__.html", null ],
    [ "sse_", "structboost_1_1simd_1_1sse__.html", null ],
    [ "ssse3_", "structboost_1_1simd_1_1ssse3__.html", null ],
    [ "vmx_", "structboost_1_1simd_1_1vmx__.html", null ],
    [ "vsx_", "structboost_1_1simd_1_1vsx__.html", null ],
    [ "xop_", "structboost_1_1simd_1_1xop__.html", null ]
];